### ISSUE TITLE
BUG? Can't find 'boot_DBD__MariaDB' in Windows/StrawberryPerl using distro DBD::MariaDB

### ISSUE THREAD

**Issue by AzaOberman** [perl5-dbi/DBD-MariaDB#165]
ERROR MESSAGE:
   Can't find 'boot_DBD__MariaDB' symbol in M:/MariaDB/lib/libMariaDB.dll

Distribution: DBD::MariaDB (repo MetaCPAN)
Module version: 1.21 

COMPLETE PERL SCRIPT TO DEMONSTRATE ERROR:
     #!/usr/bin/perl  
     use DBD::MariaDB;

ENVIRONMENT
  Windows 10 Pro (64))
    Version: 20H2
    Build: 19042.1415
    "perl -v" returns:
    Perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread
    Visual Studio 2008
  
  StrawberryPerl
    strawberry-perl-5.32.1.1-64bit installed from msii

  MariaDB:
    innodb_version                             | 10.6.5                                                                 |
    | protocol_version                          | 10                                                                      |
    | slave_type_conversions                |                                                                           |
    | system_versioning_alter_history   | ERROR                                                                |
    | system_versioning_asof               | DEFAULT                                                             |
    | tls_version                                   | TLSv1.1,TLSv1.2,TLSv1.3                                      |
    | version                                        | 10.6.5-MariaDB                                                   |
    | version_comment                        | mariadb.org binary distribution                            |
    | version_compile_machine             | x64                                                                      |
    | version_compile_os                      | Win64                                                                  |
    | version_malloc_library                  | system                                                                  |
    | version_source_revision                | 109fc67d4da46d52d2a96528eaea3b0ef6275692 |
    | version_ssl_library                        | WolfSSL 4.8.1                                                         |

    my.ini:
      [mysqld]
      datadir=M:/MariaDB/data
      port=3306
      innodb_buffer_pool_size=2038M
      [client]
      port=3306
      plugin-dir=M:/MariaDB/lib/plugin

    SELECT @@log_error returns M:\MariaDB\data\Lab02.err which is empty.

**Comment by pali** [comment]
This error means that you have compiled or installed DBD::MariaDB module incorrectly or process is incomplete. Please look into the installing documentation guide.
