### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by waldo22** [perl5-dbi/DBD-MariaDB#166]
My first attempt to switch from DBD::mysql to DBD::MariaDB was stymied by the errors `MySQL server has gone away` and `Can't locate object method "execute" via package "1" (perhaps you forgot to load "1"?)`.

I'm not sure where to even begin troubleshooting this issue, but switching back to DBD::mysql "fixed" the problem.

This is most likely something that we're doing in a non-standard way, but I would appreciate any pointers in what to look for.

**Comment by pali** [comment]
Could you please show exact code which triggered this error?
