### ISSUE TITLE
As of MySQL 8.0.34 and 8.1.0 's libmysqlclients deprecates MYSQL_OPT_RECONNECT

### ISSUE THREAD

**Issue by mroemer** [perl5-dbi/DBD-MariaDB#191]
Since Ubuntu rolled out `libmysqlclient21 8.0.34-0ubuntu0.22.04.1`, a warning is thown everytime DBD::MariaDB connects: `WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.`

This is due to the deprecation of `MYSQL_OPT_RECONNECT`, which is only used at:

https://github.com/perl5-dbi/DBD-MariaDB/blob/e81937de30824abb1b82405e86e6c4aae328ba64/dbdimp.c#L2364-L2371

See https://github.com/perl5-dbi/DBD-mysql/issues/354

Copied from there:

> The MySQL client library currently supports performing an automatic reconnection to the server if it finds that the connection is down and an application attempts to send a statement to the server to be executed. Now, this feature is deprecated and subject to removal in a future release of MySQL.
>
>The related MYSQL_OPT_RECONNECT option is still available but it is also deprecated. C API functions [mysql_get_option()](https://dev.mysql.com/doc/c-api/8.1/en/mysql-get-option.html) and [mysql_options()](https://dev.mysql.com/doc/c-api/8.1/en/mysql-options.html) now write a deprecation warning to the standard error output when an application specifies MYSQL_OPT_RECONNECT. (WL #15766)

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-34.html#mysqld-8-0-34-deprecation-removal
https://dev.mysql.com/doc/relnotes/mysql/8.1/en/news-8-1-0.html#mysqld-8-1-0-deprecation-removal

**Comment by pali** [comment]
I'm already watching the linked DBD-mysql issue. I'm planning to prepare DBD-MariaDB patches for fixing MySQL 8.x compatibility. This one is issue to fix/workaround. But the issue https://github.com/perl5-dbi/DBD-MariaDB/issues/160 is harder and I do not know what to do with it...

**Comment by pali** [comment]
Fix for this issue is ready in pull request: https://github.com/perl5-dbi/DBD-MariaDB/pull/192
