### ISSUE TITLE
failed: SSL connection error: Enforcing SSL encryption is not supported

### ISSUE THREAD

**Issue by ByteFan** [perl5-dbi/DBD-MariaDB#195]

**Comment by ByteFan** [comment]
not a bug, updated to the latest DBD/MariaDB 1.22 and looks good.

**Comment by pali** [comment]
Yea, there were more security related bugs and so it is possible that older client library or older DBD::MariaDB module is not able to establish TLS connection securely. In this case DBD::MariaDB throw an error message without attempting to send password unencrypted.
