### ISSUE TITLE
DBD-MariaDB does not check "Active" on database handles when preparing / executing

### ISSUE THREAD

**Issue by jwrightecs** [perl5-dbi/DBD-MariaDB#199]
Similar to https://github.com/perl5-dbi/DBD-mysql/pull/388 DBD-MariaDB needs to check whether a database handle is active (has not been disconnected) before attempting to  prepare or execute queries against that handle

**Comment by choroba** [comment]
Can you provide more details? The test you provided in https://github.com/perl5-dbi/DBD-mysql/issues/352#issuecomment-1792963633 correctly dies with
```
DBD::MariaDB::db prepare failed: MySQL server has gone away at ./1.pl line 10.
Can't call method "execute" on an undefined value at ./1.pl line 11.
```

**Comment by jwrightecs** [comment]
Closing this issue, there was external code setting auto_reconnect on for mariadb handle
